(()=>{'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const songs=()=>Array.isArray(window.momoSongs)?window.momoSongs:[];
function entries(){const m=new Map();for(const s of songs()){const raw=String(s?.artist||'').trim();if(!raw||/^unknown artist$/i.test(raw))continue;for(const n of raw.split(/\s*(?:;|,|\s+&\s+|\s+feat\.?\s+|\s+ft\.?\s+)\s*/i).map(x=>x.trim()).filter(Boolean)){const k=n.toLocaleLowerCase();if(!m.has(k))m.set(k,{name:n,songs:[]});m.get(k).songs.push(s)}}return[...m.values()].sort((a,b)=>a.name.localeCompare(b.name,undefined,{sensitivity:'base'}))}
function cleanExisting(){document.querySelectorAll('.momo-artists-subtitle,.momo-artists-refresh').forEach(x=>x.remove());const nav=document.getElementById('momoArtistsNav');if(nav){nav.className='momo-artists-nav';nav.innerHTML='<span class="momo-artists-icon"><svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"></circle><path d="M3.5 19c.5-3.2 2.4-5 5.5-5s5 1.8 5.5 5"></path><path d="M16 5.5a3 3 0 0 1 0 5.8"></path><path d="M16 14c2.7.2 4.3 1.9 4.7 4.8"></path></svg></span><span>Artists</span>';nav.onclick=show}}
function ensure(){const root=document.querySelector('.content')||document.querySelector('.app')||document.body;if(!root)return;let page=document.getElementById('page-artists');if(!page){page=document.createElement('main');page.id='page-artists';page.className='page momo-artists-page';page.innerHTML='<div class="momo-artists-head"><h1>Artists</h1></div><div class="momo-artists-grid" id="momoArtistsGrid"></div>';root.appendChild(page)}let nav=document.getElementById('momoArtistsNav');const host=document.querySelector('.nav')||document.querySelector('.side');if(host&&!nav){nav=document.createElement('button');nav.id='momoArtistsNav';nav.type='button';nav.className='momo-artists-nav';nav.innerHTML='<span class="momo-artists-icon"><svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"></circle><path d="M3.5 19c.5-3.2 2.4-5 5.5-5s5 1.8 5.5 5"></path><path d="M16 5.5a3 3 0 0 1 0 5.8"></path><path d="M16 14c2.7.2 4.3 1.9 4.7 4.8"></path></svg></span><span>Artists</span>';host.appendChild(nav);nav.onclick=show}cleanExisting();render()}
function render(){const g=document.getElementById('momoArtistsGrid');if(!g)return;const list=entries();if(!list.length){g.innerHTML='<div class="momo-artists-empty"><strong>No artists yet</strong><span>Import music to see your artists here.</span></div>';return}g.innerHTML=list.map((a,i)=>`<button class="momo-artist-card" data-i="${i}" type="button"><span class="momo-artist-art"><span>♪</span></span><span class="momo-artist-info"><strong>${esc(a.name)}</strong><small>${a.songs.length} ${a.songs.length===1?'song':'songs'}</small></span><span class="momo-artist-arrow">›</span></button>`).join('');g.querySelectorAll('.momo-artist-card').forEach((c,i)=>c.onclick=()=>openArtist(list[i].name))}
function show(){const p=document.getElementById('page-artists');if(!p)return;document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));p.classList.add('active');document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));document.getElementById('momoArtistsNav')?.classList.add('active');document.body.classList.remove('momo-responsive-menu','momo-menu-open');render()}
function openArtist(name){const target=[...document.querySelectorAll('.artist-link,[data-artist]')].find(x=>String(x.textContent||x.dataset.artist||'').trim().toLocaleLowerCase()===name.toLocaleLowerCase());if(target){target.click();return}const lib=[...document.querySelectorAll('.nav button')].find(x=>/library|music|songs/i.test(x.textContent||''));if(lib){lib.click();setTimeout(()=>{const t=[...document.querySelectorAll('.artist-link,[data-artist]')].find(x=>String(x.textContent||x.dataset.artist||'').trim().toLocaleLowerCase()===name.toLocaleLowerCase());t?.click()},200)}}
function disableScrobble(){for(const k of ['lastfmScrobble','lastfmScrobbleTrack','scrobbleToLastFm','sendLastFmScrobble'])if(k in window)try{window[k]=()=>false}catch{}document.querySelectorAll('[data-lastfm-scrobble],[data-scrobble-lastfm]').forEach(x=>x.remove())}
function start(){ensure();disableScrobble();let n=songs().length;setInterval(()=>{const x=songs().length;if(x!==n){n=x;render()}cleanExisting();disableScrobble()},800)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();